### ISSUE TITLE
Rails.application.load_seed fails with error

### ISSUE THREAD

**Issue by snex** [panter/seed_box#6]
Hi, I am using this gem to seed my db however when I try to run my test suite, I have a line that calls "Rails.application.load_seed" to populate the TEST db, but it fails with the following error:

```
An error occurred in a `before(:suite)` hook.
Failure/Error: Rails.application.load_seed

NoMethodError:
  undefined method `seed' for main:Object
  Did you mean?  send
```

**Comment by snex** [comment]
Workaround:

Place this into db/seeds.rb:

```
require 'seed_box'
include SeedBox
```

**Comment by koffeinfrei** [comment]
The assumption of this gem is that you use it through rake. You can see in https://github.com/panter/seed_box/blob/master/lib/tasks/seed_box.rake#L17-L18 that the rake task does the same as you suggested as a workaround. Your workaround therefore makes sense.
